[program:groovescribe]
directory=/home/fons/GrooveScribe
command=/usr/bin/node server.js
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=fons
stderr_logfile=/var/log/groovescribe.err
stdout_logfile=/var/log/groovescribe.log
stderr_logfile_maxbytes=10MB
stdout_logfile_maxbytes=10MB
stderr_logfile_backups=3
stdout_logfile_backups=3
